package de.dangoe.concurrent.slact.core.internal;

import de.dangoe.concurrent.slact.core.ActorPath;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Future;
import org.jetbrains.annotations.NotNull;

/**
 * Represents an item in an actor's mailbox.
 */
public abstract class MailboxItem {

  /**
   * Message wrapper for mailbox items.
   *
   * @param <M> The message type.
   */
  public static abstract class WrappedMessage<M> extends MailboxItem {

    private final M message;

    /**
     * Constructs a wrapped message.
     *
     * @param message The message.
     * @param sender  The sender's actor path.
     */
    protected WrappedMessage(final @NotNull M message, final @NotNull ActorPath sender) {
      super(sender);
      this.message = message;
    }

    /**
     * Returns the wrapped message.
     *
     * @return The message.
     */
    public final @NotNull M message() {
      return this.message;
    }
  }

  /**
   * Fire-and-forget message for mailbox items.
   *
   * @param <M> The message type.
   */
  public static final class FireAndForgetMessage<M> extends WrappedMessage<M> {

    /**
     * Constructs a fire-and-forget message.
     *
     * @param message The message.
     * @param sender  The sender's actor path.
     */
    public FireAndForgetMessage(final @NotNull M message, final @NotNull ActorPath sender) {
      super(message, sender);
    }
  }

  /**
   * Message with response request for mailbox items.
   *
   * @param <M> The message type.
   * @param <R> The response type.
   */
  public static final class MessageWithResponseRequest<M, R> extends WrappedMessage<M> {

    private final CompletableFuture<R> future;

    /**
     * Constructs a message with response request.
     *
     * @param message The message.
     * @param sender  The sender's actor path.
     */
    public MessageWithResponseRequest(final @NotNull M message, final @NotNull ActorPath sender) {
      super(message, sender);
      this.future = new CompletableFuture<>();
    }

    /**
     * Returns the future for the response.
     *
     * @return The response future.
     */
    public @NotNull Future<R> future() {
      return future;
    }

    /**
     * Returns the internal future for the response.
     *
     * @return The internal response future.
     */
    @NotNull CompletableFuture<R> futureInternal() {
      return future;
    }
  }

  /**
   * Lifecycle control message for mailbox items.
   */
  public static abstract class LifecycleControlMessage extends MailboxItem {

    /**
     * Constructs a lifecycle control message.
     *
     * @param sender The sender's actor path.
     */
    public LifecycleControlMessage(final @NotNull ActorPath sender) {
      super(sender);
    }
  }

  /**
   * Complete start actor command for mailbox items.
   */
  public static final class CompleteStartActorCommand extends LifecycleControlMessage {

    /**
     * Constructs a complete start actor command.
     *
     * @param sender The sender's actor path.
     */
    public CompleteStartActorCommand(final @NotNull ActorPath sender) {
      super(sender);
    }
  }

  /**
   * Command to stop an actor.
   */
  public static final class StopActorCommand extends LifecycleControlMessage {

    /**
     * Constructs a stop actor command.
     *
     * @param sender The sender's actor path.
     */
    public StopActorCommand(final @NotNull ActorPath sender) {
      super(sender);
    }
  }

  /**
   * Command to try completing the stop of an actor.
   */
  public static final class TryCompleteStopActorCommand extends LifecycleControlMessage {

    /**
     * Constructs a try-complete stop actor command.
     *
     * @param sender The sender's actor path.
     */
    public TryCompleteStopActorCommand(final @NotNull ActorPath sender) {
      super(sender);
    }
  }

  /**
   * Event indicating an actor has stopped.
   */
  public static final class ActorStoppedEvent extends LifecycleControlMessage {

    /**
     * Constructs an actor stopped event.
     *
     * @param sender The sender's actor path.
     */
    public ActorStoppedEvent(final @NotNull ActorPath sender) {
      super(sender);
    }
  }

  /**
   * Lock-free Snowflake ID generator scoped to this JVM process.
   *
   * <p>Layout (64 bits, always positive):
   * <pre>
   * | 0 | 41-bit ms timestamp | 10-bit worker | 12-bit sequence |
   * </pre>
   * The 41-bit timestamp encodes milliseconds elapsed since {@link #EPOCH}, giving ~69 years of
   * range. The 10-bit worker ID is derived from the OS process ID so that IDs generated by two
   * different JVM processes never collide. The 12-bit per-millisecond sequence allows up to 4,096
   * IDs per millisecond per process.
   */
  private static final class SnowflakeIdGenerator {

    private static final long EPOCH = 1_577_836_800_000L; // 2020-01-01T00:00:00Z

    private static final int WORKER_ID_BITS = 10;
    private static final int SEQUENCE_BITS = 12;

    private static final long MAX_WORKER_ID = (1L << WORKER_ID_BITS) - 1;  // 1023
    private static final long MAX_SEQUENCE = (1L << SEQUENCE_BITS) - 1;    // 4095

    private static final int WORKER_ID_SHIFT = SEQUENCE_BITS;
    private static final int TIMESTAMP_SHIFT = WORKER_ID_BITS + SEQUENCE_BITS;

    private final long workerIdBits;
    private long lastTimestamp = -1L;
    private long sequence = 0L;

    SnowflakeIdGenerator() {
      this.workerIdBits = (ProcessHandle.current().pid() & MAX_WORKER_ID) << WORKER_ID_SHIFT;
    }

    synchronized long next() {
      long now = System.currentTimeMillis();
      if (now < lastTimestamp) {
        now = lastTimestamp; // clock moved backwards — stay on last timestamp
      }
      if (now == lastTimestamp) {
        sequence = (sequence + 1) & MAX_SEQUENCE;
        if (sequence == 0) {
          // Sequence exhausted for this millisecond — busy-wait for the next tick.
          while (now <= lastTimestamp) {
            now = System.currentTimeMillis();
          }
        }
      } else {
        sequence = 0;
      }
      lastTimestamp = now;
      return ((now - EPOCH) << TIMESTAMP_SHIFT) | workerIdBits | sequence;
    }
  }

  private static final SnowflakeIdGenerator ID_GENERATOR = new SnowflakeIdGenerator();

  private final long id;

  private final ActorPath sender;

  protected MailboxItem(final @NotNull ActorPath sender) {
    super();
    this.id = ID_GENERATOR.next();
    this.sender = sender;
  }

  /**
   * Returns the unique identifier for this mailbox item.
   *
   * @return The item id.
   */
  public final long id() {
    return this.id;
  }

  /**
   * Returns the sender's actor path for this mailbox item.
   *
   * @return The sender's actor path.
   */
  public final @NotNull ActorPath sender() {
    return sender;
  }

  @Override
  public String toString() {
    return "%s{id=%s, sender=%s}".formatted(getClass().getSimpleName(), id, sender);
  }
}
